apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      upstream auth_service {
        server auth-service.default.svc.cluster.local:80;
      }

      upstream payments_service {
        server payments-service.default.svc.cluster.local:80;
      }

      upstream products_service {
        server products-service.default.svc.cluster.local:80;
      }

      server {
        listen 80;

        location /auth/ {
          proxy_pass http://auth_service;
        }

        location /payments/ {
          proxy_pass http://payments_service;
        }

        location /products/ {
          proxy_pass http://products_service;
        }
      }
    }